language: java
jdk:
  - oraclejdk11

before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean test
  - ./gradlew build

before_install:
  - export TZ=Brazil/East

deploy:
  provider: heroku
  app: mf-discovery-server-api
  api_key: $HEROKU_API_KEY
